name: Deploying Cloud Infrastructure Stack

on:
  push:
    branches:
      - main
      - develop
jobs:
  deploy_cloud_infrastructure:
    name: Deploying Cloud Infrastructure Stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.ADMIN_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.ADMIN_SECRET_KEY }}
            aws-region: ${{ secrets.REGION }}

      - name: Install Python Dependencies
        run: pip install -r requirements.txt
        
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}