name: Deploying Cloud Infrastructure Stack

on:
  push:
    branches:
      - main
jobs:
  deploy_cloud_infrastructure:
    name: Deploying Cloud Infrastructure Stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Python Dependencies
        run: pip install -r requirements.txt
        working-directory: ./src/cloud_infrastructure/
        
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: production
          work-dir: ./src/cloud_infrastructure/
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}